##################################################################################################
# To run this script              	                          					   				##	
# cd ~/Dropbox/Diet_EWL_BariatricSurgery_2022/analysis/BLJ_config_files	 				   				##
# biolockj --blj -d ASA24_analysis.properties				      					  			##
# biolockj --blj -d -c ASA24_analysis.properties -r ${BLJ_PROJ}/ASA24_analysis_*			 	##
##################################################################################################

# make sure memory is set to 16GB
# Docker > Preferences > Resources

genMod.launcher=Rscript
pipeline.inputTypes=other
pipeline.copyInput=Y

input.dirPaths=../data/
input.allowDuplicateNames=Y
Rfunc=../RScripts/functions.R
# metaVariables=KCAL PROT TFAT CARB


#BioModule biolockj.module.diy.GenMod AS PatientCharacteristics
PatientCharacteristics.scriptPath=../RScripts/PatientCharacteristics.R
PatientCharacteristics.param=weight_update_BLonly_excluded.txt
PatientCharacteristics.resources=${Rfunc}
PatientCharacteristics.imageOwner=asorgen
PatientCharacteristics.imageTag=v5
PatientCharacteristics.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS BMI_Results
BMI_Results.scriptPath = ../RScripts/BMI_Results.R
BMI_Results.param=weight_update_BLonly_excluded.txt
BMI_Results.resources=${Rfunc}
BMI_Results.imageOwner=asorgen
BMI_Results.imageTag=v5
BMI_Results.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS ExcessWeightLoss
ExcessWeightLoss.scriptPath = ../RScripts/ExcessWeightLoss.R
ExcessWeightLoss.param=${metaVariables}
ExcessWeightLoss.resources=${Rfunc}
ExcessWeightLoss.imageOwner=asorgen
ExcessWeightLoss.imageTag=v5
ExcessWeightLoss.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS ASA24Average
ASA24Average.scriptPath=../RScripts/ASA24Average.R
ASA24Average.imageOwner=asorgen
ASA24Average.imageTag=v4
ASA24Average.imageName=gg-tidyr
ASA24Average.param=TNS_Master_file_enrolled_5-31-22.txt

#BioModule biolockj.module.diy.GenMod AS WeightMetaMerge
WeightMetaMerge.scriptPath=../RScripts/WeightMetaMerge.R
WeightMetaMerge.imageOwner=asorgen
WeightMetaMerge.imageTag=v4
WeightMetaMerge.imageName=gg-tidyr
WeightMetaMerge.param=ASA24_metadata.tsv HEI_data.txt

#BioModule biolockj.module.diy.GenMod AS Nutrient_Analysis
Nutrient_Analysis.scriptPath = ../RScripts/Nutrient_Analysis.R
Nutrient_Analysis.resources=${Rfunc}
Nutrient_Analysis.imageOwner=asorgen
Nutrient_Analysis.imageTag=v5
Nutrient_Analysis.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Nutrient_Analysis_update
Nutrient_Analysis_update.scriptPath=../RScripts/Nutrient_Analysis_update.R
Nutrient_Analysis_update.resources=${Rfunc}
Nutrient_Analysis_update.imageOwner=asorgen
Nutrient_Analysis_update.imageTag=v5
Nutrient_Analysis_update.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Nutrient_Analysis_24mo_patients
Nutrient_Analysis_24mo_patients.scriptPath=../RScripts/Nutrient_Analysis_24mo_patients.R
Nutrient_Analysis_24mo_patients.resources=${Rfunc}
Nutrient_Analysis_24mo_patients.imageOwner=asorgen
Nutrient_Analysis_24mo_patients.imageTag=v5
Nutrient_Analysis_24mo_patients.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Prediction
Prediction.scriptPath=../RScripts/Prediction.R
Prediction.resources=${Rfunc}
Prediction.imageOwner=asorgen
Prediction.imageTag=v5
Prediction.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Barplot_summaries
Barplot_summaries.scriptPath=../RScripts/Barplot_summaries.R
Barplot_summaries.resources=${Rfunc}
Barplot_summaries.imageOwner=asorgen
Barplot_summaries.imageTag=v5
Barplot_summaries.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS Nutrient_Intake_Over_Time
Nutrient_Intake_Over_Time.scriptPath=../RScripts/Nutrient_Intake_Over_Time.R
Nutrient_Intake_Over_Time.resources=${Rfunc}
Nutrient_Intake_Over_Time.imageOwner=asorgen
Nutrient_Intake_Over_Time.imageTag=v5
Nutrient_Intake_Over_Time.imageName=gg-tidyr

#BioModule biolockj.module.diy.GenMod AS MetaLinearModeling
MetaLinearModeling.scriptPath=../RScripts/Metadata_MLM.R
MetaLinearModeling.imageOwner=asorgen
MetaLinearModeling.imageTag=v5
MetaLinearModeling.imageName=gg-tidyr
MetaLinearModeling.resources=${Rfunc}

